package org.integratedmodelling.thinklab.tests;

import junit.framework.TestCase;

import org.integratedmodelling.collections.Pair;
import org.integratedmodelling.exceptions.ThinklabException;
import org.integratedmodelling.thinklab.Thinklab;
import org.integratedmodelling.thinklab.api.annotations.Concept;
import org.integratedmodelling.thinklab.api.knowledge.ISemanticObject;
import org.integratedmodelling.thinklab.api.knowledge.ISemantics;
import org.integratedmodelling.thinklab.api.knowledge.kbox.IKbox;
import org.integratedmodelling.thinklab.metadata.Metadata;

/**
 * The class <code>ThinklabTest</code> contains tests for the class {@link
 * <code>Thinklab</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 3/12/12 8:06 PM
 *
 * @author Ferd
 *
 * @version $Revision$
 */
public class ThinklabTest extends TestCase {

	@Concept("thinklab.test:Person")
	public static class Person {
		
		String _name;
		int    _age;
		Person[] _children;
		Person[] _parents;
		Person   _partner;
		
		public Person(String name, int age, Person[] parents, Person[] children, Person partner) {
			_name = name;
			_age = age;
			_partner = partner;
			_children = children;
			_parents = parents;
		}
	}
		
	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public ThinklabTest(String name) {
		super(name);
	}

	/**
	 * Launch the test.
	 *
	 * @param args String[]
	 */
	public static void main(String[] args) {
		// add code to run tests here
	}

	/**
	 * Perform pre-test initialization
	 *
	 * @throws Exception
	 *
	 * @see TestCase#setUp()
	 */
	protected void setUp() throws Exception {
		super.setUp();
		Thinklab.boot();
	}

	@Override
	protected void tearDown() throws Exception {
		Thinklab.shutdown();
		super.tearDown();
	}

	/**
	 * Run the conceptualize test
	 */
	public void testConceptualize() {

		// add test code here
		assertTrue(true);
	}

	public void testSimpleLiterals() throws ThinklabException {
		
		ISemanticObject quaranta = Thinklab.get().annotate(40);
		ISemanticObject stocazzo = Thinklab.get().annotate("stocazzo");
		
		Object oquarant = Thinklab.get().instantiate(quaranta.getSemantics());
		Object ostocazz = Thinklab.get().instantiate(stocazzo.getSemantics());
		
		assertTrue (oquarant.equals(40) && ostocazz.equals("stocazzo"));
	}
	
	/**
	 * Run the storeLinear test
	 * @throws Exception 
	 */
	public void testStoreAcyclic() throws Exception {

		Metadata metadata = new Metadata();
		metadata.put(Metadata.DC_COVERAGE_SPATIAL, new Pair<String,String>("cazzo","bestia"));
		metadata.put(Metadata.DC_COMMENT, "Stocazzo");
		metadata.put(Metadata.DC_CONTRIBUTOR, "Piccione");
		
		ISemanticObject o = Thinklab.get().annotate(metadata);
		
		ISemantics semantics = o.getSemantics();		
		Object porco = Thinklab.get().instantiate(semantics);
		
		IKbox kbox = Thinklab.get().requireKbox("thinklab");
		if (kbox != null) {
			kbox.store(o);
		}
		
		assertTrue(
				porco instanceof Metadata && 
				((Metadata)porco).get(Metadata.DC_COMMENT).toString().equals("Stocazzo"));
	}

	/**
	 * Run the storeAcyclic test
	 * @throws Exception 
	 */
	public void testStoreCyclic() throws Exception {
		
		Person john = new Person("john", 34, null, null, null);
		Person mary = new Person("mary", 29, null, null, john);
		mary._partner = john;
		Person dick = new Person("dick", 71, null, new Person[]{mary}, null);
		Person pipp = new Person("pipp", 12, new Person[]{john, mary}, null, null);
		mary._parents = new Person[]{dick};
		pipp._parents = new Person[]{john, mary};
		
		ISemantics zio = Thinklab.get().conceptualize(dick);
		
		System.out.println(zio.asList());
//		Thinklab.get().requireKbox("thinklab").store(dick);
		// add test code here
//		assertTrue(false);
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = conceptualize, storeLinear, storeAcyclic
 * assertTrue = false
 * callTestMethod = true
 * createMain = true
 * createSetUp = true
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = org.integratedmodelling.thinklab.tests
 * package.sourceFolder = thinklab/src/tests/java
 * superclassType = junit.framework.TestCase
 * testCase = ThinklabTest
 * testClassType = org.integratedmodelling.thinklab.Thinklab
 */