/**
 * Copyright 2011 The ARIES Consortium (http://www.ariesonline.org) and
 * www.integratedmodelling.org. 

   This file is part of Thinklab.

   Thinklab is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published
   by the Free Software Foundation, either version 3 of the License,
   or (at your option) any later version.

   Thinklab is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Thinklab.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.integratedmodelling.mca.electre3.view;

import org.integratedmodelling.mca.electre3.model.Alternative;

/**
 *
 * @author  Edwin Boaz Soenaryo
 */
public class AlternativeEditPanel extends javax.swing.JPanel {

    /** Creates new form CriteriaPanel */
    public AlternativeEditPanel(E3View parent, Alternative a) {
        this.parent = parent;
        initComponents();

        setAlternativeName(a.getName());
        setDescription(a.getDescription());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfAlternativeName = new javax.swing.JTextField();
        jtfDescription = new javax.swing.JTextField();
        jbtSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jtfAlternativeName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfAlternativeName.setText("Alternative Name");

        jtfDescription.setText("Alternative extended description.");

        jbtSave.setText("Save");
        jbtSave.setOpaque(false);
        jbtSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jtfAlternativeName, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSave)
                    .addComponent(jtfAlternativeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jbtSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSaveActionPerformed
    String name = jtfAlternativeName.getText();
    String desc = jtfDescription.getText();

    parent.updateActiveAlternative(name, desc);
    parent.setEditAlternative(false);
}//GEN-LAST:event_jbtSaveActionPerformed


    public void setAlternativeName(String name) {
        jtfAlternativeName.setText(name);
    }
    
    public void setDescription(String description) {
        if (description.equals(""))
            description = "Alternative description";
        jtfDescription.setText(description);
    }
    
    private E3View parent;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtSave;
    private javax.swing.JTextField jtfAlternativeName;
    private javax.swing.JTextField jtfDescription;
    // End of variables declaration//GEN-END:variables

}
