/*
 * CriteriaPanel.java
 *
 * Created on September 8, 2008, 5:16 PM
 */

package org.integratedmodelling.mca.electre3.view;

import java.awt.Color;
import javax.swing.JOptionPane;

import org.integratedmodelling.mca.electre3.model.Criterion;

/**
 *
 * @author  Edwin Boaz Soenaryo
 */
public class CriterionEditPanel extends javax.swing.JPanel {

    /** Creates new form CriteriaPanel */
    public CriterionEditPanel(E3View parent, Criterion c) {
        this.parent = parent;
        initComponents();
        jspTableContainer.getViewport().setBackground(Color.WHITE);
        
        setCriterionName(c.getCode());
        setDescription(c.getDescription());
        setWeightValue(c.getWeight());
        setIndifferenceValue(c.getIndifferenceAlpha(), c.getIndifferenceBeta());
        setPreferenceValue(c.getPreferenceAlpha(), c.getPreferenceBeta());
        setVetoValue(c.getVetoAlpha(), c.getVetoBeta());
        setVetoEnabledValue(c.isVetoEnabled());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrPreferenceDirection = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlbWeight = new javax.swing.JLabel();
        jlbVeto = new javax.swing.JLabel();
        jlbIndifference = new javax.swing.JLabel();
        jlbPreference = new javax.swing.JLabel();
        jtfWeightValue = new javax.swing.JTextField();
        jtfIndifferenceAlphaValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfIndifferenceBetaValue = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfPreferenceAlphaValue = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfPreferenceBetaValue = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfVetoAlphaValue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfVetoBetaValue = new javax.swing.JTextField();
        jcbVetoEnabled = new javax.swing.JCheckBox();
        jlbDirection = new javax.swing.JLabel();
        jrbAscending = new javax.swing.JRadioButton();
        jrbDescending = new javax.swing.JRadioButton();
        jspTableContainer = new javax.swing.JScrollPane();
        tblAlternativeData = new javax.swing.JTable();
        jtfCriterionName = new javax.swing.JTextField();
        jtfDescription = new javax.swing.JTextField();
        jbtSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(224, 236, 255));

        jlbWeight.setFont(new java.awt.Font("Tahoma", 1, 11));
        jlbWeight.setText("Criterion weight:");

        jlbVeto.setFont(new java.awt.Font("Tahoma", 1, 11));
        jlbVeto.setText("Veto threshold:");

        jlbIndifference.setFont(new java.awt.Font("Tahoma", 1, 11));
        jlbIndifference.setText("Indifference threshold:");

        jlbPreference.setFont(new java.awt.Font("Tahoma", 1, 11));
        jlbPreference.setText("Preference threshold:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("α =");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("β =");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("α =");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("β =");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("α =");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("β =");

        jcbVetoEnabled.setFont(new java.awt.Font("Tahoma", 1, 11));
        jcbVetoEnabled.setSelected(true);
        jcbVetoEnabled.setText("Veto enabled");
        jcbVetoEnabled.setOpaque(false);

        jlbDirection.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlbDirection.setText("Preference:");

        bgrPreferenceDirection.add(jrbAscending);
        jrbAscending.setSelected(true);
        jrbAscending.setText("Ascending");
        jrbAscending.setOpaque(false);

        bgrPreferenceDirection.add(jrbDescending);
        jrbDescending.setText("Descending");
        jrbDescending.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jtfWeightValue))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jlbPreference, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbIndifference)
                                    .addComponent(jlbWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfIndifferenceBetaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfIndifferenceAlphaValue)
                            .addComponent(jtfPreferenceAlphaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPreferenceBetaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbVeto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfVetoBetaValue, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfVetoAlphaValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addComponent(jcbVetoEnabled)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbDirection)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbDescending)
                            .addComponent(jrbAscending))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jtfIndifferenceAlphaValue, jtfIndifferenceBetaValue, jtfPreferenceAlphaValue, jtfPreferenceBetaValue});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbVeto, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtfVetoAlphaValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfWeightValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbIndifference, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jtfIndifferenceAlphaValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfIndifferenceBetaValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbVetoEnabled))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jlbPreference, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPreferenceAlphaValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbDirection)
                            .addComponent(jrbAscending))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfPreferenceBetaValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbDescending)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jtfVetoBetaValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jspTableContainer.setBackground(new java.awt.Color(195, 217, 255));
        jspTableContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 217, 255), 2));
        jspTableContainer.setOpaque(false);

        tblAlternativeData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Alternative", "g(j)", "q(j)", "p(j)", "v(j)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlternativeData.setGridColor(new java.awt.Color(195, 217, 255));
        tblAlternativeData.setOpaque(false);
        jspTableContainer.setViewportView(tblAlternativeData);

        jtfCriterionName.setFont(new java.awt.Font("Tahoma", 1, 14));
        jtfCriterionName.setText("Criterion Name");

        jtfDescription.setText("Criterion extended description.");

        jbtSave.setText("Save");
        jbtSave.setOpaque(false);
        jbtSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jspTableContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jtfCriterionName, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSave)
                    .addComponent(jtfCriterionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jspTableContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void jbtSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSaveActionPerformed
    try {
        String name = jtfCriterionName.getText();
        String desc = jtfDescription.getText();
        double weight = Double.parseDouble(jtfWeightValue.getText());
        double inda = Double.parseDouble(jtfIndifferenceAlphaValue.getText());
        double indb = Double.parseDouble(jtfIndifferenceBetaValue.getText());
        double prea = Double.parseDouble(jtfPreferenceAlphaValue.getText());
        double preb = Double.parseDouble(jtfPreferenceBetaValue.getText());
        double veta = Double.parseDouble(jtfVetoAlphaValue.getText());
        double vetb = Double.parseDouble(jtfVetoBetaValue.getText());
        boolean vetoEnabled = jcbVetoEnabled.isSelected();
        boolean ascending = jrbAscending.isSelected();
        
        parent.updateActiveCriterion(name, desc, weight, inda, indb, prea, preb,
                veta, vetb, vetoEnabled, ascending);
        parent.setEditCriterion(false);
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error parsing input values.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_jbtSaveActionPerformed


    public void setCriterionName(String name) {
        jtfCriterionName.setText(name);
    }
    
    public void setDescription(String description) {
        if (description.equals(""))
            description = "Criterion description";
        jtfDescription.setText(description);
    }
    
    public void setWeightValue(double weight) {
        jtfWeightValue.setText(Double.toString(weight));
    }
    
    public void setIndifferenceValue(double alpha, double beta) {
        jtfIndifferenceAlphaValue.setText(Double.toString(alpha));
        jtfIndifferenceBetaValue.setText(Double.toString(beta));
    }
    
    public void setPreferenceValue(double alpha, double beta) {
        jtfPreferenceAlphaValue.setText(Double.toString(alpha));
        jtfPreferenceBetaValue.setText(Double.toString(beta));
    }
    
    public void setVetoValue(double alpha, double beta) {
        jtfVetoAlphaValue.setText(Double.toString(alpha));
        jtfVetoBetaValue.setText(Double.toString(beta));
    }
    
    public void setVetoEnabledValue(boolean vetoEnabled) {
        jcbVetoEnabled.setSelected(vetoEnabled);
    }
    
    public void setDirectionValue(boolean ascending) {
        if (ascending) {
            jrbAscending.setSelected(true);
        } else {
            jrbDescending.setSelected(true);
        }
    }
    
    private E3View parent;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrPreferenceDirection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtSave;
    private javax.swing.JCheckBox jcbVetoEnabled;
    private javax.swing.JLabel jlbDirection;
    private javax.swing.JLabel jlbIndifference;
    private javax.swing.JLabel jlbPreference;
    private javax.swing.JLabel jlbVeto;
    private javax.swing.JLabel jlbWeight;
    private javax.swing.JRadioButton jrbAscending;
    private javax.swing.JRadioButton jrbDescending;
    private javax.swing.JScrollPane jspTableContainer;
    private javax.swing.JTextField jtfCriterionName;
    private javax.swing.JTextField jtfDescription;
    private javax.swing.JTextField jtfIndifferenceAlphaValue;
    private javax.swing.JTextField jtfIndifferenceBetaValue;
    private javax.swing.JTextField jtfPreferenceAlphaValue;
    private javax.swing.JTextField jtfPreferenceBetaValue;
    private javax.swing.JTextField jtfVetoAlphaValue;
    private javax.swing.JTextField jtfVetoBetaValue;
    private javax.swing.JTextField jtfWeightValue;
    private javax.swing.JTable tblAlternativeData;
    // End of variables declaration//GEN-END:variables

}
