/**
 * Copyright 2011 The ARIES Consortium (http://www.ariesonline.org) and
 * www.integratedmodelling.org. 

   This file is part of Thinklab.

   Thinklab is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published
   by the Free Software Foundation, either version 3 of the License,
   or (at your option) any later version.

   Thinklab is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Thinklab.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.integratedmodelling.mca.electre3.view;

import java.awt.Color;

import org.integratedmodelling.mca.electre3.model.AAPair;
import org.integratedmodelling.mca.electre3.model.Alternative;
import org.integratedmodelling.mca.electre3.model.MatrixModel;

/**
 *
 * @author  Edwin Boaz Soenaryo
 */
public class MatrixView extends javax.swing.JPanel {

    /** Creates new form MatrixView */
    public MatrixView(E3View parent) {
        this.parent = parent;
        initComponents();
        tblConcordanceMatrix.setEnabled(false);
        jspConcordanceContainer.getViewport().setBackground(Color.WHITE);
    }

    public void setModel(MatrixModel cm) {
        concordances = new TwoHeadersTableModel();
        Object[] alternatives = parent.getDisplayedAlternatives();

        int rows = alternatives.length + 1;
        String[][] data = new String[rows][rows];
        data[0][0] = "";
        int i = 1;
        concordances.addColumn(null);
        for (int ai = 0; ai < alternatives.length; ai++) {
            Alternative a = (Alternative) (alternatives[ai]);
            data[0][i++] = a.getName();
            concordances.addColumn(a);
        }
        concordances.addRow(data[0]);

        i = 0;
        for (int ai1 = 0; ai1 < alternatives.length; ai1++) {
            Alternative a1 = (Alternative) (alternatives[ai1]);
            data[++i][0] = a1.getName();
            int j = 1;
            for (int ai2 = 0; ai2 < alternatives.length; ai2++) {
                Alternative a2 = (Alternative) (alternatives[ai2]);
                AAPair aa = new AAPair(a1, a2);
                double perf = cm.getValue(aa);
                data[i][j++] = ViewSettings.getDecimalFormat().format(perf);
            }
            concordances.addRow(data[i]);
        }
        tblConcordanceMatrix.setModel(concordances);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspConcordanceContainer = new javax.swing.JScrollPane();
        tblConcordanceMatrix = new javax.swing.JTable();

        setOpaque(false);

        jspConcordanceContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(195, 217, 255), 2));

        tblConcordanceMatrix.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblConcordanceMatrix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConcordanceMatrix.setColumnSelectionAllowed(true);
        tblConcordanceMatrix.setGridColor(new java.awt.Color(195, 217, 255));
        tblConcordanceMatrix.setRowHeight(24);
        tblConcordanceMatrix.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblConcordanceMatrix.setTableHeader(null);
        jspConcordanceContainer.setViewportView(tblConcordanceMatrix);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspConcordanceContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspConcordanceContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private E3View parent;
    private TwoHeadersTableModel concordances;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jspConcordanceContainer;
    private javax.swing.JTable tblConcordanceMatrix;
    // End of variables declaration//GEN-END:variables

}
